### ISSUE TITLE
NULL_AFTER_DEREF in test/integration.c

### ISSUE THREAD

**Issue by g-coder** [jpommerening/midikit#16]
In file test/integration.c at #157
Pointer 'driver' is dereferenced which can be NULL.

Solution:
ASSERT_NOT_EQUAL( driver,  NULL, "Could not create driver." );
should come before 
driver->send = &_send;

![patch1](https://cloud.githubusercontent.com/assets/10647613/10908032/9e7cea78-8254-11e5-9d1f-4ba3bdddece9.jpg)

**Comment by jpommerening** [comment]
Oops, I missed that one.
Can you send a pull request for this?

**Comment by garima-g** [comment]
commit a280ab4b5f6a134031c7c129af3c9af6e4574d70

**Comment by jpommerening** [comment]
Commit mentioned above is in PR #18. Merged, fixed, thanks ;)
