### ISSUE TITLE
dereference of null in osc.c and rtp.c

### ISSUE THREAD

**Issue by g-coder** [jpommerening/midikit#17]
In driver/common/rtp.c
Pointer 'peer' returned from function 'malloc' at #286 may be null, and it is dereferenced at #287.

Pointer 'session' returned from function 'malloc' at #433 may be null, and it is dereferenced at #435.

Solution:
Pointer ‘peer’ and Pointer ‘session’ should be checked for NULL after malloc.

In driver/osc/osc.c
Pointer 'driver' returned from function 'malloc' at #44 may be null, and it is dereferenced at #46.

Solution:
Pointer ‘driver’ should be checked for NULL after malloc.

**Comment by garima-g** [comment]
![patch1](https://cloud.githubusercontent.com/assets/10647613/10909646/98cdc5e6-8260-11e5-9694-d0a91b796b1c.jpg)

**Comment by jpommerening** [comment]
You're absolutely right!
Would you min sending a pull request for that?

**Comment by garima-g** [comment]
Created pull request #20

**Comment by jpommerening** [comment]
Fixed via #20. Thanks! :)
