### ISSUE TITLE
Build with travis CI on every pull request or commit

### ISSUE THREAD

**Issue by g-coder** [jpommerening/midikit#19]
This enhancement will automatic check and test the changes done. It will improve the testing capability of component as build can be tested at every pull request before commit.

To enable this feature , you will have to login in https://travis-ci.org/. using github account 
and enable the travis feature for the midikit library.

Many other github projects use this feature. Hope it will help midikit too.

**Comment by garima-g** [comment]
commit dc3b97df531e59c0226cb2709113fd6f60bfa281

**Comment by jpommerening** [comment]
Fixed via #18
